[package]
name = "serde-value"
version = "0.0.1"
authors = ["arcnmx"]

description = "Serialization value trees"
documentation = "http://arcnmx.github.io/serde-value/serde_value/"
repository = "https://github.com/arcnmx/serde-value"
readme = "README.md"
keywords = ["serde"]
license = "MIT"

[dependencies]
serde = "0.6"
ordered-float = "0.0"
